#!/bin/bash
ip link set dev eth0 up
ip addr add 192.168.177.130/25 dev eth0
ip link set dev eth1 up
ip addr add 129.27.249.2/26 dev eth1

echo 1 >/proc/sys/net/ipv4/ip_forward
ip route add 192.168.177.128/25 via 192.168.177.130

ip route add default via 129.27.249.1 dev eth1
#Activer le dhcp sur la box
service isc-dhcp-server start
#la masquerade:
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
####Partie filtrage : on acceptera les requetes ICMP-HTTP-FTP-DNS-DHCP####
#tout ce qui n'est pas explicitement autorisé est interdit 
iptables -P FORWARD DROP
iptables -P INPUT DROP
iptables -P OUTPUT DROP
#Accepter les pings(ICMP)
iptables -A FORWARD -p icmp -j ACCEPT
iptables -A INPUT -p icmp -j ACCEPT
iptables -A OUTPUT -p icmp -j ACCEPT
#Autoriser l'accès aux réponses/requetes HTTP
iptables -A FORWARD -p tcp -s 0/0 -d 129.27.249.194/26 --sport 80 -m state --state ESTABLISHED -j ACCEPT
iptables -A FORWARD -p tcp -s 129.27.249.194/26 -d 0/0 --dport 80 -m state --state ESTABLISHED -j ACCEPT
#Ajouter les régles pour acceder au DNS (en TCP et UDP)
iptables -A FORWARD -p udp -d 129.27.249.196/26 --dport 53 -j ACCEPT
iptables -A FORWARD -p udp -s 129.27.249.196/26 --sport 53 -j ACCEPT
iptables -A FORWARD -p tcp -d 129.27.249.196/26 --dport 53 -j ACCEPT
iptables -A FORWARD -p tcp -s 129.27.249.196/26 --sport 53 -j ACCEPT
#Ajouter les régles pour acceder au FTP
iptables -A FORWARD -p tcp -s 129.27.249.195/26 --sport 21 -j ACCEPT
iptables -A FORWARD -p tcp -d 129.27.249.195/26 --dport 21 -j ACCEPT
iptables -A FORWARD -p udp -s 129.27.249.195/26 --sport 21 -j ACCEPT
iptables -A FORWARD -p udp -d 129.27.249.195/26 --dport 21 -j ACCEPT
#Ajouter les régles pour autoriser le DHCP
iptables -A INPUT -i eth0 -p udp --dport 67:68 --sport 67:68 -j ACCEPT
iptables -A INPUT -i eth0 -p tcp --dport 67:68 --sport 67:68 -j ACCEPT

