#!/bin/bash
ip link set dev eth0 up
ip addr add 129.27.249.196/26 dev eth0

ip route add default via 129.27.249.193 dev eth0
#Activer le service DNS du FAI :
service bind9 start
chmod -R /etc/bind
chown -R bind:bind/etc/bind
service bind9 restart
