#!/bin/bash
ip link set dev eth0 up
ip addr add 192.168.177.129/25 dev eth0

ip route add default via 192.168.177.130 dev eth0
#dhclient eth0

echo "nameserver 129.27.249.196" >> /etc/resolv.conf

#dig www.rachida.com pour tester dns

#pour tester FTP
#wget --user=rachida --password='rachida' ftp://129.27.249.195/mesage.txt
